name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          # only do one Deb file because they're so large
          - FROM:     'debian:buster'
          - FROM:     'opensuse/leap'
          - FROM:     'fedora:36'
          - FROM:     'fedora:35'
          - FROM:     'fedora:34'
          - FROM:     'rockylinux/rockylinux'
          - FROM:     'manjarolinux/base'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout HEAD^2
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   'clang'
        FLAGS:      ''
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS
