name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Source tarballs only
          - FROM:     'ubuntu:focal'
            ARTIFACT_EXT: 'tar.[xb]z*'
          # only build one Deb File b/c they're so large
          - FROM:     'debian:buster'
            ARTIFACT_EXT: 'deb'
          - FROM:     'opensuse/leap'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:36'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:35'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:34'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux/rockylinux'
            ARTIFACT_EXT: 'rpm'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # where in a pull request we want to move to the head of the PR and not be at the
    # merge commit; here we want to be at the HEAD of the ref

    - name: Extract tag name etc
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
    - name: Test tag name etc
      run: |
        echo "${TAG_NAME}"
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   'clang'
        FLAGS:      ''
        MY_OS_NAME: linux
        IS_RELEASE: 1
      run: script/cibuild $FLAGS
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTIFACT_EXT: ${{ matrix.ARTIFACT_EXT }}
      with:
        args: "packages/*.${{ matrix.ARTIFACT_EXT }}"
