name: Windows-CI

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2019
            is-release:      0
          - os:              windows-2022
            is-release:      0

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install CMake
        uses: lukka/get-cmake@acb35cf920333f4dc3fc4f424f1b30d5e7d561b4 #v3.31.4
        with:
          cmakeVersion: 3.31.4

      - name: Build it
        run: script/build
